- name: pausing for 10 seconds
  pause:
    seconds: 10

- name: changing user in httpd.conf
  replace:
    path: "{{ dir_app_http }}/conf/httpd.conf"
    regexp: 'User nobody'
    replace: 'User {{apache_user}}'

- name: changing group in httpd.conf file
  replace:
    path: "{{ dir_app_http }}/conf/httpd.conf"
    regexp: 'Group nobody'
    replace: 'Group {{apache_group}}'

- name: changing port in httpd.conf file
  replace:
    path: "{{ dir_app_http }}/conf/httpd.conf"
    regexp: 'Listen 80'
    replace: 'Listen {{apache_port}}'

- name: Change permission for IBM directory
  shell: "chown -R webadm:webgrp {{mount_point}} && chmod -R 755 {{mount_point}}"

- name: "Start Apache"
  shell: |
    /bin/su - webadm -c "{{dir_app_http}}/bin/apachectl -k start"
    exit 0
  register: startApache

- name: Change permission for IBM directory
  shell: "chown -R webadm:webgrp {{mount_point}} && chmod -R 755 {{mount_point}}"
  
- name: Check installation if exists
  shell: |
     {{dir_install_mgr}}/eclipse/tools/imcl listInstalledPackages | wc -l
     exit 0
  register: pscheck

- name: Display output
  debug: var=pscheck.stdout

- name: Failing the playbook because installation does not exists
  fail:
    msg: "Error: Webserver not successfully installed"
  when: pscheck.stdout < "3"
