- name: Delete apache package in Source path
  file:
    path: /appl/Source/apache.tar.gz
    state: absent
  when: (apache_package_extracted.changed == true and apache_package_extracted.extract_results.rc == 0 )
