---
- name: Ensure /appl/IBM exists
  stat:
    path: /appl/IBM
  register: file_system_appl_IBM_exists

- name: Fail the execution if /appl/IBM does not exists
  fail:
    msg: Failing the execution due to /appl/IBM does NOT EXISTS !!
  when: not file_system_appl_IBM_exists.stat.exists

#  - name: Ensure /appl/IBM/WebSphere/ exists
#    stat:
#      path: /appl/IBM/WebSphere/
#    register: file_system_appl_IBM_WebSphere_exists

#  - name: Fail the execution if /appl/IBM/WebSphere/ does not exists
#    fail:
#      msg: Failing the execution due to /appl/IBM/WebSphere/ does NOT EXISTS !!
#    when: not file_system_appl_IBM_WebSphere_exists.stat.exists

- name: Ensure /appl/Source exists
  stat:
    path: /appl/Source
  register: file_system_Source_exists

- name: Fail the execution if /appl/Source does not exists
  fail:
    msg: Failing the execution due to /appl/Source does NOT EXISTS !!
  when: not file_system_Source_exists.stat.exists
